### ISSUE TITLE
样式有问题，偶尔会变形

### ISSUE THREAD

**Issue by Ancoding** [renjianan/RecyclerBanner#2]
**# 左右滑动一会偶现样式变形，左右间距不对** 
不知道怎么贴上手机截图，我这边有变形的截图，这是一个很大的bug

**Comment by AnCoding** [comment]
**嗨，你好，我找到复现步骤了，就是你长按一个图片慢慢的向左滑，滑小于1/2距离放开它会回弹然后显示，这个时候展示就变形了，希望对你修复有帮助，哈哈**

**Comment by AnCoding** [comment]
**这个bug，必现的哟**

**Comment by renjianan** [comment]
已修复，感谢

**Comment by AnCoding** [comment]
群主微信号吗多少，我有个问题想请教一下？

**Comment by AnCoding** [comment]
这个demo还存在一个bug，就是横向轮播点击事件有时候没反应，点了好几次才有反应，这是一个严重的问题

**Comment by renjianan** [comment]
改好了，加QQ吧330047649
