### ISSUE TITLE
获得当前位置

### ISSUE THREAD

**Issue by zhangheshuai** [renjianan/RecyclerBanner#31]
请问如何获得当前position

**Comment by haoyuegongzi** [comment]
什么意思？没看明白

在 2018-11-25 10:27:50，"zhangheshuai" <notifications@github.com> 写道：


请问如何获得当前position

**Comment by zhangheshuai** [comment]
就是一个数组banear 现在滑动我想知道滑动到第几个position 假如直接调用mRecyclerView.addOnScrollListener 数据会混乱的
