### ISSUE TITLE
How to show total 5 items?

### ISSUE THREAD

**Issue by sagarmaiyad** [renjianan/RecyclerBanner#32]
Currently, its showing only 3 items. but i want to display 5 items. how can i get that?

**Comment by haoyuegongzi** [comment]
没看明白你要表述的问题，能否用中文啊，老哥

At 2018-12-05 13:33:38, "Slake" <notifications@github.com> wrote:


Currently, its showing only 3 items. but i want to display 5 items. how can i get that?

**Comment by sagarmaiyad** [comment]
它解決了，謝謝你的回复。
