### ISSUE TITLE
左滑动有bug

### ISSUE THREAD

**Issue by dazeGitHub** [renjianan/RecyclerBanner#5]
老哥，你这个demo有个bug，向左滑动时有时会滑动好几张，我用这个到项目中时，不知道怎么回事有时向左一下滑动4，5张，根本停不下来，，

**Comment by AnCoding** [comment]
估计是吃了炫迈，哈哈

**Comment by hardstruglling** [comment]
这个项目是自动轮播图，如果不滑动recycleview则不会回调mRecyclerView.addOnScrollListener而是直接进入handler处理。
左滑滑动的item毫无规律，有时先向右滑几张然后再向左滑动几张，有时一直在滑动，停不下来，debug追踪下代码，发现问题出在：
@Override
    public int scrollHorizontallyBy(int dx, RecyclerView.Recycler recycler, RecyclerView.State state) {
        Log.i(TAG,"dx  "+dx);
        if (mOrientation == VERTICAL) {
            return 0;
        }
        return scrollBy(dx, recycler, state);
    }
右滑的时候dx值返回正常，左滑的时候dx会不断的输出值而且有正数有负数，而这个方法是重写LayoutManager的方法，这个项目并没有对dx这个值做处理，推测可能是LayoutManager的问题

**Comment by hardstruglling** [comment]
这个项目是自动轮播图，如果不滑动recycleview则不会回调mRecyclerView.addOnScrollListener而是直接进入handler处理。
左滑滑动的item毫无规律，有时先向右滑几张然后再向左滑动几张，有时一直在滑动，停不下来，debug追踪下代码，发现问题出在：
@Override
    public int scrollHorizontallyBy(int dx, RecyclerView.Recycler recycler, RecyclerView.State state) {
        Log.i(TAG,"dx  "+dx);
        if (mOrientation == VERTICAL) {
            return 0;
        }
        return scrollBy(dx, recycler, state);
    }
右滑的时候dx值返回正常，左滑的时候dx会不断的输出值而且有正数有负数，而这个方法是重写LayoutManager的方法，这个项目并没有对dx这个值做处理，推测可能是LayoutManager的问题

**Comment by hardstruglling** [comment]
这个项目是自动轮播图，如果不滑动recycleview则不会回调mRecyclerView.addOnScrollListener而是直接进入handler处理。
左滑滑动的item毫无规律，有时先向右滑几张然后再向左滑动几张，有时一直在滑动，停不下来，debug追踪下代码，发现问题出在：
@Override
    public int scrollHorizontallyBy(int dx, RecyclerView.Recycler recycler, RecyclerView.State state) {
        Log.i(TAG,"dx  "+dx);
        if (mOrientation == VERTICAL) {
            return 0;
        }
        return scrollBy(dx, recycler, state);
    }
右滑的时候dx值返回正常，左滑的时候dx会不断的输出值而且有正数有负数，而这个方法是重写LayoutManager的方法，这个项目并没有对dx这个值做处理，推测可能是LayoutManager的问题

**Comment by hardstruglling** [comment]
这个项目是自动轮播图，如果不滑动recycleview则不会回调mRecyclerView.addOnScrollListener而是直接进入handler处理。
左滑滑动的item毫无规律，有时先向右滑几张然后再向左滑动几张，有时一直在滑动，停不下来，debug追踪下代码，发现问题出在：
@Override
    public int scrollHorizontallyBy(int dx, RecyclerView.Recycler recycler, RecyclerView.State state) {
        Log.i(TAG,"dx  "+dx);
        if (mOrientation == VERTICAL) {
            return 0;
        }
        return scrollBy(dx, recycler, state);
    }
右滑的时候dx值返回正常，左滑的时候dx会不断的输出值而且有正数有负数，而这个方法是重写LayoutManager的方法，这个项目并没有对dx这个值做处理，推测可能是LayoutManager的问题
