### ISSUE TITLE
横向左滑有bug

### ISSUE THREAD

**Issue by hardstruglling** [renjianan/RecyclerBanner#7]
这个项目是自动轮播图，如果不滑动recycleview则不会回调mRecyclerView.addOnScrollListener而是直接进入handler处理。
左滑滑动的item毫无规律，有时先向右滑几张然后再向左滑动几张，有时一直在滑动，停不下来，debug追踪下代码，发现问题出在：
@override
public int scrollHorizontallyBy(int dx, RecyclerView.Recycler recycler, RecyclerView.State state) {
Log.i(TAG,"dx "+dx);
if (mOrientation == VERTICAL) {
return 0;
}
return scrollBy(dx, recycler, state);
}
右滑的时候dx值返回正常，左滑的时候dx会不断的输出值而且有正数有负数，而这个方法是重写LayoutManager的方法，这个项目并没有对dx这个值做处理，推测可能是LayoutManager的问题
大神看下这个问题是什么原因造成的？

**Comment by renjianan** [comment]
正常情况，dx左滑都是正数，右滑都是负数。我的手机正常滑动并没有出现这个问题。请问有详细的复现过程吗？

**Comment by hardstruglling** [comment]
我使用的测试机是360午诺 android6.0系统，在MainActivity中横向banner当左滑的时候，dx值得变化：
01-29 10:03:38.685 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 17
01-29 10:03:38.703 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 17
01-29 10:03:38.719 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 22
01-29 10:03:38.735 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 24
01-29 10:03:38.802 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 48
01-29 10:03:38.835 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1100
01-29 10:03:38.851 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1600
01-29 10:03:38.865 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1400
01-29 10:03:38.882 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1600
01-29 10:03:38.865 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1400
01-29 10:03:38.882 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1600
01-29 10:03:38.899 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:38.915 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:38.932 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:38.948 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1100
01-29 10:03:38.965 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
01-29 10:03:38.982 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
01-29 10:03:38.999 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1600
01-29 10:03:39.015 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
01-29 10:03:39.032 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
01-29 10:03:39.049 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1600
01-29 10:03:39.065 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1100
01-29 10:03:39.082 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:39.099 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1600
01-29 10:03:39.115 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:39.132 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:39.149 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1600
01-29 10:03:39.165 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx 1700
01-29 10:03:39.182 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1500
01-29 10:03:39.199 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1600
01-29 10:03:39.215 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
01-29 10:03:39.232 16478-16478/com.renny.recyclerbanner I/BannerLayoutManager: scrollHorizontallyBy: dx -1700
log太多只粘出部分的信息，有时会一直闪烁只能把进程干掉，如果不用惯性，而是手值一直按住屏幕左滑到下一个item则完全正常，使用惯性手指快速左滑一下，则会出现不停的图片闪烁

**Comment by renjianan** [comment]
分辨率的原因，请将左右两张图片至少显示1/3空间。修改item_image布局的宽度

**Comment by hardstruglling** [comment]
按照您说的修改item的宽度可以正常完美左滑，建议大神可以动态的根据手机屏幕宽度来设置item的宽度，以便更好地适配其它机型

**Comment by hardstruglling** [comment]
按照您说的修改item的宽度可以正常完美左滑，建议大神可以动态的根据手机屏幕宽度来设置item的宽度，以便更好地适配其它机型

**Comment by renjianan** [comment]
是的，非常感谢你提的问题。我会继续改进。

**Comment by hardstruglling** [comment]
recyleview功能确实很强大，在您分享的这个项目学到recycleview更多的知识
