### ISSUE TITLE
可以增加个改变滑动速度的方法

### ISSUE THREAD

**Issue by Kunsan16** [renjianan/RecyclerBanner#8]
@Override
    public void smoothScrollToPosition(RecyclerView recyclerView, RecyclerView.State state, int position) {
        LinearSmoothScroller linearSmoothScroller = new LinearSmoothScroller(recyclerView.getContext()) {

            //This returns the milliseconds it takes to
            //scroll one pixel.
            @Override
            protected float calculateSpeedPerPixel(DisplayMetrics displayMetrics) {
                return MILLISECONDS_PER_INCH / displayMetrics.density;
            }
        };
        linearSmoothScroller.setTargetPosition(position);
        startSmoothScroll(linearSmoothScroller);
    }

 public void setSpeedSlow() {
        MILLISECONDS_PER_INCH = context.getResources().getDisplayMetrics().density * 0.7f;
    }

我在BannerLayoutManager加了滑动速度控制的方法，但是
在图片快滑动到最中间时，会突然加快一下，找不出原因，大神帮忙看下原因

**Comment by renjianan** [comment]
已经加了
